services:
  app:
    build: .
    container_name: car_marketplace_app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=car_marketplace
      - REDIS_ADDR=redis:6379

  db:
    image: postgres:17
    container_name: car_marketplace_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_marketplace
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: car_marketplace_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
